IF NOT EXISTS (
   SELECT name
   FROM sys.databases
   WHERE name = N'QUIZNIGHT'
)
CREATE DATABASE QUIZNIGHT

CREATE TABLE QUIZ
	(QId TINYINT PRIMARY KEY,
	QType VARCHAR(20) UNIQUE,
	QDescription VARCHAR(200) )

CREATE TABLE ANSWER
	(AId INT,
	AText VARCHAR(30),
	APoints INT,
	CONSTRAINT PK_ANSWER PRIMARY KEY (AId) )

CREATE TABLE QUESTION
	(QuId INT,
	QuText VARCHAR(100),
	QDifficulty VARCHAR(20),
	AnId INT,
	CONSTRAINT PK_QUESTION PRIMARY KEY (QuId),
	CONSTRAINT FK_QUESTION_ANSWER FOREIGN KEY (AnId)
	REFERENCES ANSWER(AId)
	ON UPDATE CASCADE
	ON DELETE NO ACTION )

CREATE TABLE CONSISTS_OF
	(QuesId INT NOT NULL,
	QId TINYINT NOT NULL,
	CONSTRAINT PK_QUIZ_QUESTION PRIMARY KEY (QuesId, QId),
	CONSTRAINT FK_CONSISTS_OF_QUESTION FOREIGN KEY ("QuesId")
	REFERENCES QUESTION(QuId),
	CONSTRAINT FK_CONSISTS_OF_QUIZ FOREIGN KEY ("QId")
	REFERENCES QUIZ(QId) )

CREATE TABLE VENUE
	(VId INT PRIMARY KEY,
	VName VARCHAR(30),
	VLocation VARCHAR(30),
	Capacity INT )

ALTER TABLE QUIZ
	ADD VenueId INT,
		CONSTRAINT FK_QUIZ_VENUE FOREIGN KEY("VenueId")
		REFERENCES VENUE(VId)
		ON UPDATE CASCADE
		ON DELETE NO ACTION;

CREATE TABLE TEAM
	(TId INT PRIMARY KEY,
	TName VARCHAR(30),
	TotalPoints INT )

CREATE TABLE ATTENDS
	(QuizId TINYINT,
	TeamId INT,
	CONSTRAINT PK_QUIZ_TEAM PRIMARY KEY (QuizId, TeamId),
	CONSTRAINT FK_ATTENDS_QUIZ FOREIGN KEY ("QuizId")
	REFERENCES QUIZ(QId),
	CONSTRAINT FK_ATTENDS_TEAM FOREIGN KEY ("TeamId")
	REFERENCES TEAM(TId) )

CREATE TABLE PARTICIPANT
	(PId INT NOT NULL,
	PFirstName VARCHAR(20),
	PLastName VARCHAR(20),
	Age INT,
	City VARCHAR(20),
	TeamId INT,
	CONSTRAINT PK_PARTICIPANT PRIMARY KEY (PId),
	CONSTRAINT FK_PARTICIPANT_TEAM FOREIGN KEY (TeamId)
	REFERENCES TEAM(TId) )

CREATE TABLE PRIZE
	(PrizeId INT NOT NULL,
	PType VARCHAR(30),
	PValue INT,
	CONSTRAINT PK_PRIZE PRIMARY KEY(PrizeId) )

ALTER TABLE QUIZ
	ADD PrizeId INT,
		CONSTRAINT FK_QUIZ_PRIZE FOREIGN KEY(PrizeId)
		REFERENCES PRIZE(PrizeId);

CREATE TABLE SPONSOR
	(SponsorId INT,
	SType VARCHAR(20),
	SName VARCHAR(30),
	CONSTRAINT PK_SPONSOR PRIMARY KEY(SponsorId) )

ALTER TABLE PRIZE
	ADD SponsorId INT,
		CONSTRAINT FK_PRIZE_SPONSOR FOREIGN KEY(SponsorId)
		REFERENCES SPONSOR(SponsorId);